# Generated by Django 3.1.5 on 2021-01-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingFarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Bunny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('age', models.FloatField(verbose_name='Age')),
                ('furr_color', models.CharField(max_length=255, verbose_name='Furr color')),
                ('breeding_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.breedingfarm', verbose_name='Breeding farm')),
            ],
            options={
                'verbose_name': 'Bunny',
                'verbose_name_plural': 'Bunnies',
            },
        ),
    ]
